### PR TITLE
rename babelrc to babel.config (closes #130)

### LINKED ISSUE #130: Rename .babelrc to babel.config.json
See https://babeljs.io/docs/en/config-files - in babel 7 they're now encouraging using `babel.config.json`, which we should switch to.

### PR DESCRIPTION
**Pull request by zanza00**
Here is a nice PR to get started.

I have some tests that are failing and I am not so sure on how to continue in fixing them.

here is an example 

```
[test:e2e]   ● typescript root config usage › Can yarn build
[test:e2e]
[test:e2e]     expect(received).toMatch(expected)
[test:e2e]
[test:e2e]     Expected pattern: /org-root-config.js/
$ webpack --mode=production
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command."
[test:e2e]
[test:e2e]       23 |         console.log(result.stderr);
[test:e2e]       24 |         expect(result.stdout).toMatch(/webpack --mode=production/);
[test:e2e]     > 25 |         expect(result.stdout).toMatch(/org-root-config.js/);
[test:e2e]          |                               ^
[test:e2e]       26 |       })
[test:e2e]       27 |       .code(0)
[test:e2e]       28 |       .end(done);
[test:e2e]
[test:e2e]       at Array.<anonymous> (tests/e2e/root-config-ts-webpack.test.js:25:31)
[test:e2e]       at ChildProcess.<anonymous> (node_modules/nixt/lib/nixt/runner.js:437:37)
[test:e2e]
[test:e2e]   ● typescript root config usage › Can yarn lint
[test:e2e]
[test:e2e]     Expected value   undefined
[test:e2e]     Received:
[test:e2e]       127
[test:e2e]
[test:e2e]     Message:
[test:e2e]       `yarn lint`: Expected exit code: "0", actual: "127"
[test:e2e]
[test:e2e]     Difference:
[test:e2e]
[test:e2e]       Comparing two different types of values. Expected undefined but received number.
[test:e2e]
[test:e2e]       at error (node_modules/nixt/lib/nixt/expectations.js:151:13)
[test:e2e]       at Array.<anonymous> (node_modules/nixt/lib/nixt/expectations.js:25:14)
[test:e2e]       at ChildProcess.<anonymous> (node_modules/nixt/lib/nixt/runner.js:437:37)
[test:e2e]       at node_modules/nixt/lib/nixt/batch.js:137:5
[test:e2e]       at next (node_modules/nixt/lib/nixt/batch.js:144:5)
[test:e2e]       at node_modules/nixt/lib/nixt/batch.js:131:33
[test:e2e]       at ChildProcess.<anonymous> (node_modules/nixt/lib/nixt/runner.js:441:7)
[test:e2e]```

### CODE REVIEW

**Comment by zanza00** [comment]
The tests don't fail on the CI. I don't know why.

**Comment by joeldenning** [comment]
The code looks good - the stacktrace you shared indicates that `yarn build` and `yarn lint` failed inside of the ts-root-config e2e test.

The tests passing in Travis indicates that perhaps you need to clean your e2e fixtures test directory before running the tests again. The fixtures directory is not destroyed/recreated during every test run so that every test run doesn't take several minutes. You can read more about that at https://github.com/single-spa/create-single-spa/blob/master/CONTRIBUTING.md.

Could you confirm clearing out your fixtures directory and rerunning the tests locally results in a successful test run? The code looks good but I'd hate to merge in code that only works in Travis and not locally

**Comment by filoxo** [comment]
I was able to pull this down locally and test it. I'm also getting those errors. I think one of them is that `yarn format` is modifying babel.config.js and the test is expecting the files to already be formatted.

**Comment by joeldenning** [comment]
We should modify the template files such that they are not modified during `yarn format` - that way the generated project passes `yarn lint` and we don't rely on test execution order for the tests to pass.

The best way to test might be to do `cd tests/e2e/fixtures/ts-root-config` and then run `yarn lint`, `yarn build`, etc manually

**Comment by zanza00** [comment]
The tests are flaky, I have executed them three times on my machine with `yarn test` and the third time failed.

I cd in the directory that failed and notice that the installation process was not run.

```
~/dev/create-single-spa/tests/fixtures/react-app-js-webpack master*
❯ yarn lint
yarn run v1.22.4
warning package.json: No license field
$ eslint src --ext js
/bin/sh: eslint: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/dev/create-single-spa/tests/fixtures/react-app-js-webpack master*
❯ yarn lint
yarn run v1.22.4
warning package.json: No license field
$ eslint src --ext js
/bin/sh: eslint: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

when manually installing the packages in that directory and relaunching only the e2e tests they work.

**Comment by joeldenning** [comment]
Hmm the tests have not been flaky for my machine or in the CI over the last month or so. I will pull this down and test it out locally. Perhaps it's related to a difference in our local environments? I will pull down this branch and run the tests a few times to see.

**Comment by joeldenning** [comment]
I ran the tests 8 times locally and the error occurred one time on this PR branch. I don't know what is causing it. The `yarn install` occurs as part of us calling `this.installDependencies()`. I'm going to merge this in because I don't think this is caused by the code changes here.

**Comment by filoxo** [comment]
I agree, this change looks good to me. Thanks for your contribution @zanza00!

**Pull request merged**
