### PR TITLE
Upgrade lib versions

### LINKED ISSUE #204: Upgrade to systemjs@6.7.0 and remove `named-exports` extra
As of systemjs@6.7.0, the named-exports extra is included in the `system.js` build. We should upgrade and then remove the `named-exports.js` references in create-single-spa

### PR DESCRIPTION
**Pull request by filoxo**
Resolves #204 by upgrading SystemJS, as well as single-spa, import-map-overrides, and regenerator-runtime.

### CODE REVIEW

**Comment by filoxo** [comment]
I'll look into the test failures tomorrow.

**Review by joeldenning — APPROVED** [review]
This looks good. The test failures seem related to the svelte e2e test, which is unrelated to the changes here.

**Comment by denniscalazans** [comment]
Guys, pleeeeease.

**Comment by joeldenning** [comment]
> Guys, pleeeeease.

This comment isn't helpful, and seems to imply that our volunteer labor is inadequate or slow. Feel free to contribute with code contributions, if you'd like to see changes to this project.

**Comment by denniscalazans** [comment]
> > Guys, pleeeeease.
> 
> This comment isn't helpful, and seems to imply that our volunteer labor is inadequate or slow. Feel free to contribute with code contributions, if you'd like to see changes to this project.

Unfortunately you got it completely wrong. 
It's the exact opposite.

But if it only works for you this way, 
I can just wish that you relax, man.

You guys do an amazing job.

Who's the champion here?
It's you.

**Pull request merged**
